trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  azureSubscription: 'azure-conn'
  appName: 'demologindash'

steps:
- script: |
    echo "=== Repo structure ==="
    find . -type f | grep -v ".git"
  displayName: 'Show repo files'

- script: |
    cd "DASHBORD PAGE"
    zip -r ../app.zip .
    cd ..
    echo "=== Zip contents ==="
    unzip -l app.zip
  displayName: 'Zip static site only'

- task: AzureWebApp@1
  displayName: 'Deploy to Azure App Service'
  inputs:
    azureSubscription: $(azureSubscription)
    appType: webApp
    appName: $(appName)
    package: app.zip
