trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  azureSubscription: 'azure-conn'
  appName: 'demologindash'

steps:
- script: |
    find . -type f | grep -v ".git"
  displayName: 'Show repo files'

- script: |
    cd "DASHBORD PAGE/login page"
    zip -r ../../app.zip .
    cd ../..
    unzip -l app.zip
  displayName: 'Zip static site'

- task: AzureRmWebAppDeployment@4
  displayName: 'Deploy to Azure'
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: $(azureSubscription)
    appType: 'webApp'
    WebAppName: $(appName)
    packageForLinux: 'app.zip'
    enableCustomDeployment: true
    DeploymentType: 'zipDeploy'
    TakeAppOfflineFlag: true
